### ISSUE TITLE
Create front page

### ISSUE THREAD

**Issue by erikhofer** [erikhofer/GrowthLectures#8]
* search bar (redirects to search page)
* short description -> what is Growth Lectures?
* 5 most recently added lectures
* 5 most popular lectures
* 5 most popular categories
* 5 most popular lecturers

All top lists have a "view all" link. Top lists should be cached and recomputed regularly.

**Comment by lollokiel** [comment]
Close. #8

**Comment by lollokiel** [comment]
Close. #8
